/* Generated By:JavaCC: Do not edit this line. ProjectConstants.java */
package compilerproject;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProjectConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CLASS = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int OPEN_CURL_BRACE = 8;
  /** RegularExpression Id. */
  int CLOSE_CURL_BRACE = 9;
  /** RegularExpression Id. */
  int SEMI_COLON = 10;
  /** RegularExpression Id. */
  int EQUAL = 11;
  /** RegularExpression Id. */
  int LESS = 12;
  /** RegularExpression Id. */
  int GREATER = 13;
  /** RegularExpression Id. */
  int PLUS = 14;
  /** RegularExpression Id. */
  int MINUS = 15;
  /** RegularExpression Id. */
  int GET = 16;
  /** RegularExpression Id. */
  int END = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int OUTPUT = 20;
  /** RegularExpression Id. */
  int MULTIPLICATION = 21;
  /** RegularExpression Id. */
  int DIVISION = 22;
  /** RegularExpression Id. */
  int NUMBER = 29;
  /** RegularExpression Id. */
  int ID = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int EOL = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Class\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"get_value\"",
    "\"end\"",
    "\"if\"",
    "\"else\"",
    "\"print\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
    "\"char\"",
    "\"byte\"",
    "\"int\"",
    "\"long\"",
    "\"double\"",
    "<NUMBER>",
    "<ID>",
    "<DIGIT>",
    "\".\"",
  };

}
